### ISSUE TITLE
Where do i place "for x in range(0, len(content[i]), 3):" ?

### ISSUE THREAD

**Issue by WK-GiHu** [DeathResister/ASCII-RLE#3]
@DeathResister 

1. Before the line 149
  https://github.com/DeathResister/ASCII-RLE/blob/9c617ed26674cce77e14954ff9fff76f88f4bf53/Frames%20-%20Tkinter.py#L149

    add
    ```
     message = []
    ```
2. after the line 149, add
    ```
    message.append(str(int(content[i][x:x+2]) * content[i][x+2]))
    ```
3. after the line 152, add
https://github.com/DeathResister/ASCII-RLE/blob/9c617ed26674cce77e14954ff9fff76f88f4bf53/Frames%20-%20Tkinter.py#L152
    ```
    .messagebox.showinfo(..., message='\n'.join(message))
    ```

**Comment by DeathResister** [comment]
Hey the problem i'm getting now is: 

"
    message.append(str(int(content[i][x:x+2]) * content[i][x+2]))
ValueError: invalid literal for int() with base 10: ',a'
"

**Comment by WK-GiHu** [comment]
@DeathResister 

### Please update allways [`Frames - Tkinter.py`](https://github.com/DeathResister/ASCII-RLE/blob/master/Frames%20-%20Tkinter.py) so i can review your edits.

**Comment by WK-GiHu** [comment]
@DeathResister 

https://github.com/DeathResister/ASCII-RLE/issues/4#issuecomment-579827897
>Why do I not get any errors when running in Python?

***That could not be `True`***.

Disable the line  150
https://github.com/DeathResister/ASCII-RLE/blob/3d2bcbb7719214db1881c7f4f1957272c899715b/Frames%20-%20Tkinter.py#L150

Disable line 152
https://github.com/DeathResister/ASCII-RLE/blob/3d2bcbb7719214db1881c7f4f1957272c899715b/Frames%20-%20Tkinter.py#L152

Enable line  151
https://github.com/DeathResister/ASCII-RLE/blob/3d2bcbb7719214db1881c7f4f1957272c899715b/Frames%20-%20Tkinter.py#L151

Run again.

---

>how do you suggest we fix it?

Show me the requested `binary` output or upload the compressed file.

**Comment by DeathResister** [comment]
,ad888888888888888888888888888888888888888888888888888888888da,
d                                                             b
8                                             ,ad8888888888 8 8
8                                             d88888888'    8 8
8        db        ,ad8888ba,          db     8888"'      "88 8
8       d88b      d8"'    `"8b        d88b    888'       '888 8
8      d8'`8b    d8'        `8b      d8'`8b   8"       '88888 8
8     d8'  `8b   88          88     d8'  `8b  ' d888888888888 8
8    d8YaaaaY8b  88          88    d8YaaaaY8b  d88888888888P  8
8   d8""""""""8b Y8,    "88,,8P   d8""""""""8b                8
8  d8'        `8b Y8a.    Y88P   d8'        `8b               8
8 d8'          `8b `"Y8888Y"Y8a d8'          `8b              8
q                                                             p
`Y88888888888888888888888888888888888888888888888888888888888Y`

**Comment by DeathResister** [comment]
[](https://github.com/DeathResister/ASCII-RLE/blob/master/LogoASCII.txt)

[](https://github.com/DeathResister/ASCII-RLE/blob/master/LogoRLE.txt)
