### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ',a'

### ISSUE THREAD

**Issue by WK-GiHu** [DeathResister/ASCII-RLE#4]
Hey the problem i'm getting now is: 

"
    message.append(str(int(content[i][x:x+2]) * content[i][x+2]))
ValueError: invalid literal for int() with base 10: ',a'
"

The RLE looks like this:

01,01a01d57801d01a01,
01d61 01b
01845 01,01a01d10801 01801 018
01845 01d08801'04 01801 018
01808 01d01b08 01,01a01d04801b01a01,10 01d01b05 04801"01'06 01"02801 018
01807 01d02801b06 01d01801"01'04 01`01"01801b08 01d02801b04 03801'07 01'03801 018
01806 01d01801'01`01801b04 01d01801'08 01`01801b06 01d01801'01`01801b03 01801"07 01'05801 018
01805 01d01801'02 01`01801b03 02810 02805 01d01801'02 01`01801b02 01'01 01d12801 018
01804 01d01801Y04a01Y01801b02 02810 02804 01d01801Y04a01Y01801b02 01d11801P02 018
01803 01d01808"01801b01 01Y01801,04 01"02802,01801P03 01d01808"01801b16 018
01802 01d01801'08 01`01801b01 01Y01801a01.04 01Y02801P03 01d01801'08 01`01801b15 018
01801 01d01801'10 01`01801b01 01`01"01Y04801Y01"01Y01801a01 01d01801'10 01`01801b14 018
01q61 01p
01`01Y59801Y01`

_Originally posted by @DeathResister in https://github.com/DeathResister/ASCII-RLE/issues/3#issuecomment-579392301_

**Comment by WK-GiHu** [comment]
@DeathResister 

>ValueError: invalid literal for int() with base 10: ',a'

I'm confused, your function is named: `def compressP()` but your wrote ***The RLE looks like this:***?

The shown ***The RLE looks like this:***:
- [ ] Is RLE and have to be **decompressed**
- [ ] Is the content, which have to be RLE encoded

**Comment by DeathResister** [comment]
The program is supposed to read the **RLE** and then DEcompress it to ASCII and display it. The file it reads is a RLE file. Sorry about the confusion with the function name

**Comment by WK-GiHu** [comment]
@DeathResister 

>DEcompress it to ASCII 

OK, just for clarification, the result should be (... == 57): 
`01,01a01d57801d01a01,` => `,ad888888...88888888da,`  

- [ ] Yes
- [ ] No

Your output shows NewLine
What about the NewLines?

- [ ] Should be skipped
- [ ] Should be preserved as is
- [ ] Don't know ...

**Comment by DeathResister** [comment]
The new lines need to be displayed as new lines (like the RLE file) in the message box.

Thanks

**Comment by WK-GiHu** [comment]
@DeathResister 

### I get the following `encoding` errors:
```
Error line:6 item:"1"" char:"0"
Error line:7 item:"1b" char:"0"
Error line:10 item:"1b" char:"0"
Error line:11 item:"1b" char:"0"

Line 6
01807 01d02801b06 01d01801"01'04 0101"01801b08 01d02801b04 03801'07
                                    ^
```
Line 7, 10, 11
Do we have to deal with HEX values?

- [ ] Yes
- [ ] No
- [ ] Dont't know

If `Yes`, then gives:
```
Error line:6 item:"1"" char:"0"
Error line:7 item:"1'" char:"0"
Error line:10 item:"1Y" char:"0"
Error line:11 item:""0" char:"1"
```

**Comment by DeathResister** [comment]
Why is this so much more complicated in tkinter?, i didn't need to think of this when it ran in Python fine.

I'm not really sure what you mean by hex values?, the file read is going to be run length encoding of a text file containing any user data - I guess that could be HEX but i don't think so.

Sorry, It's just seeming a lot more complicated but of course if you are suggesting this as an upgrade for my current code then thanks a lot but I don't really want to trouble you too much.

Thanks again

**Comment by WK-GiHu** [comment]
@DeathResister 

>Why is this so much more complicated in tkinter?, i didn't need to think of this when it ran in Python fine.

There is **no** `tkinter` part involved yet.
Running your `def compressP` without any `tkinter` i get the same error which is pure Phyton.
The provided data are corrupt.

>I'm not really sure what you mean by hex values?,

RLE is implemented by defining a `max` length value, e.g. `255` which is HEX(FF).

---

Open the file in `binary` mode and show the output:
```
with (open(<your file name>, 'rb') as fh:
    print(fh.read())
```

**Comment by DeathResister** [comment]
Why do I not get any errors when running in Python?, the data I was given to display is not mine, It's from the project assigner. I wouldn't think they would give a corrupt data file but how do you suggest we fix it?

**Comment by WK-GiHu** [comment]
@DeathResister 

>Why do I not get any errors when running in Python?

***That could not be `True`***.

Disable the line  150
https://github.com/DeathResister/ASCII-RLE/blob/3d2bcbb7719214db1881c7f4f1957272c899715b/Frames%20-%20Tkinter.py#L150

Disable line 152
https://github.com/DeathResister/ASCII-RLE/blob/3d2bcbb7719214db1881c7f4f1957272c899715b/Frames%20-%20Tkinter.py#L152

Enable line  151
https://github.com/DeathResister/ASCII-RLE/blob/3d2bcbb7719214db1881c7f4f1957272c899715b/Frames%20-%20Tkinter.py#L151

Run again.

---

>how do you suggest we fix it?

Show me the requested `binary` output.

**Comment by DeathResister** [comment]
This is the full code (in the python file which i am trying to adapt to tkinter to make the program better) :

`def convToASCII():
    RLEfile = input("Enter RLE File to convert ASCII: ")
    ab = 1
    while ab == 1:
        try:
            with open(f"{RLEfile}.txt") as f:
                content = f.readlines()#Opens file
            ab = 0
        except (FileNotFoundError, OSError):
            rle = input("No file found \nPlease enter the name of the RLE file: ")
    content = [x.strip() for x in content]
    for i in range(0,len(content)):
        for x in range(0, len(content[i]), 3):
            print(int(content[i][x:x+2]) * content[i][x+2], end="")
        print()
`

When in a proper python file like that it works perfectly. Obviously I have accidentally missed out something (Sorry about that) and so **_Can you please look at the new Frames - Tkinter.py_** as i have made some adjustments which render the program no longer giving out an invalid literal error but still does not work properly; It now prints out the ASCII in multiple message boxes, leaving the user with a very annoying time having to click OK multiple times and the image appearing completely wrong. It there a way to fix this?

**Comment by WK-GiHu** [comment]
@DeathResister 

>now prints out the ASCII in multiple message boxes

Outdent this line
https://github.com/DeathResister/ASCII-RLE/blob/6aadf0d5d9a73843c93b3612005a8c3e1921cf6e/Frames%20-%20Tkinter.py#L151
to the level of this line
https://github.com/DeathResister/ASCII-RLE/blob/6aadf0d5d9a73843c93b3612005a8c3e1921cf6e/Frames%20-%20Tkinter.py#L146

Move this line
https://github.com/DeathResister/ASCII-RLE/blob/6aadf0d5d9a73843c93b3612005a8c3e1921cf6e/Frames%20-%20Tkinter.py#L147
before  this line
https://github.com/DeathResister/ASCII-RLE/blob/6aadf0d5d9a73843c93b3612005a8c3e1921cf6e/Frames%20-%20Tkinter.py#L146
