### ISSUE TITLE
 how can we present it like the LogoASCII

### ISSUE THREAD

**Issue by WK-GiHu** [DeathResister/ASCII-RLE#6]
Wow, now it just shows it as a long message box (tall), making the 'art' unrecognisable.

Maybe going about this via message box is not the right thing?, What do you suggest because at the moment it's not going the direction I hoped.

Just for clarification the LogoRLE **IS** the compressed version of the LogoASCII so how can we present it like the LogoASCII

_Originally posted by @DeathResister in https://github.com/DeathResister/ASCII-RLE/issues/5#issuecomment-580196459_

**Comment by WK-GiHu** [comment]
@DeathResister 

>shows it as a long message box (tall)

Yes, the `.join(...` ist spliting at character and not at line. 
See my code below, adding `_line`.

>Maybe going about this via message box is not the right thing?

Yes, you need also the option to set a `monospaced` font.

```
    message = []
    for i in range(0, len(content)):
        _line = []
        for x in range(0, len(content[i]), 3):
            row = str(int(content[i][x:x + 2]) * content[i][x + 2])
            _line.append(row)
        message.append('\n'.join(_line))
    message = '\n'.join(message)

    asciiShown = tk.Text(self, font=('Consolas', 10), wrap="none", borderwidth=0, width=64, height=14)
    asciiShown.insert('1.0', message)
    asciiShown.pack()
```

If you want a `Toplevel` Window, use this approach: [Print tabular formated text into a tk.Text widget](https://stackoverflow.com/a/59346200/7414759)

**Comment by DeathResister** [comment]
The text message is perfect but it's not the same format as the LogoASCII text...

**Comment by WK-GiHu** [comment]
@DeathResister 

>... but it's not the same format as the LogoASCII text

I have verified, didn't any difference?
Explain in more detail or show a screenshoot.

**Comment by DeathResister** [comment]
https://gyazo.com/d6b9ea10b3d3e589d4fa0fc92a5b128d

Thats what it looks like, not like the LogoASCII file.

Iv'e updated the file

**Comment by WK-GiHu** [comment]
@DeathResister 
![grafik](https://user-images.githubusercontent.com/22146250/73452892-289a8b80-436b-11ea-9977-997702781a08.png)

My bad, this
```
message.append('\n'.join(_line))
```
should read
```
message.append(''.join(_line))
```

**Comment by DeathResister** [comment]
Perfect, Thanks soo much.

I hate to ask more from you but is it possible that you could help me with the rest of the project?, If I post issues here will you have the time to respond?, I really hate to ask so much of you of course so, if you can't i completely understand.

**Comment by WK-GiHu** [comment]
@DeathResister 

> is it possible that you could help me with the rest of the project?, If I post issues here will you have the time to respond?,

Feel free to do so.
Upvote the linked answer: [Print tabular formated text into a tk.Text widget](https://stackoverflow.com/a/59346200/7414759) and consider to delete your question: [tkinter-showing-a-message](https://stackoverflow.com/questions/59917321/tkinter-showing-a-message)
