### ISSUE TITLE
DisplayASCII

### ISSUE THREAD

**Issue by DeathResister** [DeathResister/ASCII-RLE#7]
How can i display the text file contents [(LogoASCII)](https://github.com/DeathResister/ASCII-RLE/blob/master/LogoASCII.txt) to the text widget without any decompressing/compressing.

**I've updated the Frames - Tkinter.py** with what I think is somewhat correct. However, It doesn't seem to be working and comes up with: 

```
 message.append(''.join(_line))
TypeError: sequence item 0: expected str instance, _io.TextIOWrapper found
```

**Comment by DeathResister** [comment]
@WK-GiHu ?

**Comment by DeathResister** [comment]
So I got it to work, as in it displays the LogoASCII. However, my only problem is with the resetting of the  text after going back to the main menu. This is still the same issue as the Decompress To ASCII we worked on, do you know how to fix it?

**Comment by WK-GiHu** [comment]
@DeathResister 

>my only problem is with the resetting of the text after going back to the main menu.

I assume you want to delete all content inside `tk.Text(...`?
Use:
```
asciiShown.delete(1.0, tk.END)
```
Read:
[Tkinter.Text.delete-method](http://effbot.org/tkinterbook/text.htm#Tkinter.Text.delete-method)

**Comment by DeathResister** [comment]
Hey the only problem with my current code at the moment is that it's not really working as intended with `asciiShown.delete(1.0, tk.END)`.

The problem is that when i go back to the option after clicking "Go To Main Menu", there is a text box which is empty,; I want it to completely reset if that's possible. Any ideas?

Thanks

**Comment by WK-GiHu** [comment]
@DeathResister 

>with `asciiShown.delete(1.0, tk.END)`.

I see no `.delete(...` have you updated the file?

---

>I want it to completely reset if that's possible

Do you mean by ***reset***, to `destroy` the `tk.Text` widget?

On the `Frame` **`convToASCII`** you have `Label`, `Button` and `Entry` therefore the `tk.Text` widget should also defined within the `def __init__`. As it stands you create a new `tk.Text` on every call to `def compressP` which leads to stacking widgets.

**Comment by DeathResister** [comment]
line 220 - `        mButton = tk.Button(self, text="Go to the Main Menu", fg="red",
                           command=lambda: [controller.show_frame("MainMenu"), asciiShown.delete(1.0, tk.END)])`

**Comment by DeathResister** [comment]
By reset i mean that as soon as the user clicks the **"Go To Main Menu"**, the DisplayASCII will completely restart - asking the user to reenter the name of the text file and clicking submit.

I understand what you mean but the code is still not working, I feel like `asciiShown.delete(1.0, tk.END)` is not the right code but I am not really sure. Any ideas about how to do this?

**Comment by WK-GiHu** [comment]
@WK-GiHu 

>line 220 -

OK, I'm looking on the wrong line.
You can, by click on the Line Number, copy a Permalink to insert in the comment.
Hmm, looks ok?

---

>By reset i mean that as soon as the user clicks the "Go To Main Menu", the DisplayASCII will completely restart - asking the user to reenter the name of the text file and clicking submit.

Click on `"Go To Main Menu"` => ***"asking the user to reenter"***.
This makes no sense, `"Go To Main Menu"` means go to `MainMenu`?

Didn't the `Frame DisplayASCII` with the widgets show up?

**Comment by DeathResister** [comment]
When the user enters the text file name, clicks submit, and ascii is displayed properly then (right now) when the user clicks the "Go To Main Menu" button - which takes them to the Main Menu frame - after the ascii is displayed, the program displays all the options, if the user clicks on the same option again - in this case **Display ASCII** - the user will be presented with a empty tkinter text box which is not what I want. I want it so that he can completely enter a new file and click submit, etc..

Thanks

**Comment by WK-GiHu** [comment]
@DeathResister 

>I want it so that he can completely enter a new file and click submit, etc..

You have
https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L186
and 
https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L190

### Did these widgets show up?
- [ ] Yes
  - [ ] But the previous `filename` are shown in the `tk.Entry` widget
  - [ ] The `tk.Entry` widget is empty.
- [ ] No

----

If **YES**, can you enter a new filename and click `[Submit]`?
- [ ] Yes
- [ ] No

---
If **YES**, did the contents of the new file shown in the `tk.Text` widget?
- [ ] Yes
- [ ] No

**Comment by DeathResister** [comment]
After it displays the ASCII, when i click on the main menu and go back, the only thing that appears is this: https://gyazo.com/0575a99da7ac1c42fb5881647b7b33fb

**Comment by WK-GiHu** [comment]
@DeathResister 

![grafik](https://user-images.githubusercontent.com/22146250/73680646-e8b20c00-46bc-11ea-94c9-14144fcc3d28.png)
 The other widgets are behind the `tk.Text` as you have mixed `.place` with `.pack`. 

1. Move this Line 217
https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L217
below Line 194
https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L194
      ### Keep in mind, the `tk.Text` widget have to be layouted only once.

2. Before Line 183
https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L183
    add 
     ```
    leb = tk.Frame(self)
    leb.pack()
    ```
3. Make the `leb Frame` the `parent` of the following **3 widgets**.
Change from `(self, ...` to `(leb, ...` at the following **3 statements**:
  - https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L183
  - https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L186
  - https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L190

4. You have to adjust **ALL** the `x=` values, as now `x` is releativ to `leb Frame`.
  I assume you can start with `x = 20`
  https://github.com/DeathResister/ASCII-RLE/blob/f32b162a3b78af867de23457f140b3aaf816628a/Frames%20-%20Tkinter.py#L184

**Comment by DeathResister** [comment]
asciiShown.pack()
UnboundLocalError: local variable 'asciiShown' referenced before assignment

Hmm?

**Comment by WK-GiHu** [comment]
@DeathResister 

### Review
I wrote: **Move this line**, now it's doubled, remove Line 220.
https://github.com/DeathResister/ASCII-RLE/blob/aca9f9361eea23521718d6aa82168847a6c3f904/Frames%20-%20Tkinter.py#L220


>    asciiShown.pack()
UnboundLocalError: local variable 'asciiShown' referenced before assignment

I wrote: ***below Line***, you can't use a variable before it is defined.
Move Line 196 **below** Line 197
https://github.com/DeathResister/ASCII-RLE/blob/aca9f9361eea23521718d6aa82168847a6c3f904/Frames%20-%20Tkinter.py#L196

>KeyError: 'displayASCII'

Seems a follow up error as `class displayASCII` can't instantiated

**Comment by DeathResister** [comment]
Still exact same errors, Any ideas?

**Comment by WK-GiHu** [comment]
@DeathResister 

>Still exact same errors,

Yes, the statement in Line 197 is still **before** the variable `asciiShown` are defined.

https://github.com/DeathResister/ASCII-RLE/blob/474ca84c5df74131f1662ef372f0666e523d6aa0/Frames%20-%20Tkinter.py#L197

### What did you not understand from the error message?
### `... local variable 'asciiShown' referenced before assignment`

**Comment by DeathResister** [comment]
Oh, sorry I see what you mean by below, I thought you meant below as in on line 96.

Even if I move it to there it now just displays and empty tkinter widget the same as the old picture I posted, no submit or entry widget any more

**Comment by WK-GiHu** [comment]
@DeathResister 

>It is usually not a good idea to use place for ordinary window and dialog layouts; its simply to much work to get things working as they should. Use the pack or grid managers for such purposes.

Read [When to use the Place Manager](http://effbot.org/tkinterbook/place.htm)

---

Using `place` inside of `leb Frame` does not expand the `lbl Frame`, you have to define the `size` by yourself. Change:
```
        leb = tk.Frame(self, height=150)
        leb.pack(expand=True, fill=tk.BOTH, pady=10)

```

**Comment by DeathResister** [comment]
Thanks, I have adapted the code in accordance to what you said. I feel like now it is a lot better as I have placed the text widget under the **Submit** and made the frame bigger overall.

All I ask is if you could run over the [other issue](https://github.com/DeathResister/ASCII-RLE/issues/8) of **Enter RLE**

**Comment by WK-GiHu** [comment]
@DeathResister 

Ok, close this Issue if the topic `DisplayASCII` is solved
