### ISSUE TITLE
EnterRLE - def inputRLE():

### ISSUE THREAD

**Issue by WK-GiHu** [DeathResister/ASCII-RLE#9]
https://github.com/DeathResister/ASCII-RLE/blob/170062e6628a0366b8e3059e47213c6eaf981d5b/Frames%20-%20Tkinter.py#L120

Also I am completely unsure what you want me to do with the EnterRLE.

> Did this `print(...` show up in the console?

Like I said: 

> I think if you try to run it will help you to understand how to better fix the problems.

Yes it does show it in the Python shell, however, it does not help as to how to fix the problem. Please can you try to fix the EnterRLE() for it to work because currently I am completely unsure what you expect me to do.

_Originally posted by @DeathResister in https://github.com/DeathResister/ASCII-RLE/issues/8#issuecomment-582879998_

**Comment by WK-GiHu** [comment]
@DeathResister 

>Yes it does show it in the Python shell, however, it does not help as to how to fix the problem. 

I can't belive that, because I'm getting:
```
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    inputRLE()
  File "main.py", line 19, in inputRLE
    print(int(rle[i][x:x+2]) * rle[i][x+2], end="")
IndexError: string index out of range
```
you probably seeing the output from:
https://github.com/DeathResister/ASCII-RLE/blob/170062e6628a0366b8e3059e47213c6eaf981d5b/Frames%20-%20Tkinter.py#L122

### Show this output here, if the following changes didn't succeded.

---

- [ ] Move Lines 128, 129 => **to Line 123**
https://github.com/DeathResister/ASCII-RLE/blob/170062e6628a0366b8e3059e47213c6eaf981d5b/Frames%20-%20Tkinter.py#L128
https://github.com/DeathResister/ASCII-RLE/blob/170062e6628a0366b8e3059e47213c6eaf981d5b/Frames%20-%20Tkinter.py#L129

- [ ] Change to
    ```
    rle = [x.strip() for x in content.split('\n')]
    ```

**Comment by DeathResister** [comment]
I see what you mean, It seems I was getting it from 

>  print('rel:{}'.format(rle)) 

But still now the `**asciiShown**`  text widget does not display anything

**Comment by WK-GiHu** [comment]
@DeathResister 

>text widget does not display anything

You have added `state="disabled"`,  a disabled `tk.Text` widget can't updated.
You have to `enabel` in `def inputRLE()` and after the `for ...` loop you have to `disable`.
I will lookup about the `state = (readonly)`

**Comment by DeathResister** [comment]
Thanks, that works great.

Only thing is if it's possible that every line in the **`asciiInputted`** text widge it a new line in the **`asciiShown`** text widget. Currently it displays it like [this](https://gyazo.com/b637154145b1e94bfcdf65c4a18cb2e2).

I would like it like **[this](https://gyazo.com/d9e2b7ada7bb0be49a2894e062ad6676)** - (I edited the bottom text widget to be how it should be) -.

Thanks

**Comment by WK-GiHu** [comment]
@DeathResister 

>every line in the asciiInputted text widget is a new line in the asciiShown text widget - the same format

This should be the default.
You are missing a NewLine
- [ ] Insert, to be in sync with the `print(...` statements,  after Line 128
https://github.com/DeathResister/ASCII-RLE/blob/17b68886f5f1bd48cd1a10f179c20efb523fcd27/Frames%20-%20Tkinter.py#L128
    ```
    asciiShown.insert(tk.END, '\n')
    ```

**Comment by DeathResister** [comment]
Thanks so much, This has worked perfectly and I do not believe I need any more help. Of course if you can check up on here every so often it would be very appreciated.

Thanks again very much
